import 'package:drift/drift.dart';
import 'app_database.dart';
import 'default_categories.dart';

/// Stepwise migrations. Each future schema bump adds a `from: N` branch.
///
/// `onUpgrade` uses explicit `Migrator.createTable(...)` calls rather than
/// drift's `stepByStep()` helper: `stepByStep()` requires schema-version code
/// generated by the `drift_dev schema` CLI, and that CLI does not compile in
/// this environment (drift_dev 2.34.0 against drift 2.34.2).
MigrationStrategy buildMigration(AppDatabase db) => MigrationStrategy(
      onCreate: (m) async {
        await m.createAll();
        // Both single-row tables' `id` column defaults to 0 and repositories
        // address the row via `id.equals(0)`. SQLite treats a lone INTEGER
        // column PRIMARY KEY as a rowid alias, so when the id column is
        // omitted from an INSERT, SQLite auto-assigns the next rowid (1)
        // instead of honouring the column's DEFAULT 0 clause. Passing
        // `id: Value(0)` explicitly ensures the seeded row actually lands at
        // id 0.
        await db.into(db.appMetaTable).insert(
              AppMetaTableCompanion.insert(
                id: const Value(0),
                installedAt: DateTime.now(),
              ),
            );
        await db
            .into(db.appSettingsTable)
            .insert(const AppSettingsTableCompanion(id: Value(0)));
        await _seedDefaultCategories(db);
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // v1 -> v2: add the accounts/ledger/categories/recurring tables.
          // `createTable` works without the drift schema CLI (only
          // `stepByStep` needs it), so we create each new table explicitly.
          await m.createTable(db.accountsTable);
          await m.createTable(db.categoriesTable);
          await m.createTable(db.transactionsTable);
          await m.createTable(db.recurringIncomePlansTable);
          await _seedDefaultCategories(db);
        }
        if (from < 3) {
          // v2 -> v3: category budget columns and variable budget + safety
          // buffer settings. (This branch originally also created the two
          // bucket-allocation tables; those were dropped in v7 along with the
          // rest of the abstract-bucket system — see the `from < 7` branch.)
          //
          // Each `addColumn` is guarded by `_hasColumn`: when this branch
          // runs in the same `onUpgrade` pass as `from < 2` (e.g. a v1
          // install jumping straight to v3), `createTable` above already
          // built `categories_table` using today's full Dart column set (this
          // codebase can't use drift's versioned schema CLI — see the class
          // doc comment — so `createTable` has no historical snapshot to
          // build from), meaning the "new" v3 columns already exist and a
          // second `ADD COLUMN` would throw "duplicate column name".
          if (!await _hasColumn(m, 'categories_table', 'kind')) {
            await m.addColumn(db.categoriesTable, db.categoriesTable.kind);
          }
          if (!await _hasColumn(m, 'categories_table', 'monthly_limit_minor')) {
            await m.addColumn(
                db.categoriesTable, db.categoriesTable.monthlyLimitMinor);
          }
          if (!await _hasColumn(m, 'categories_table', 'weekly_limit_minor')) {
            await m.addColumn(
                db.categoriesTable, db.categoriesTable.weeklyLimitMinor);
          }
          if (!await _hasColumn(
              m, 'app_settings_table', 'variable_budget_minor')) {
            await m.addColumn(
                db.appSettingsTable, db.appSettingsTable.variableBudgetMinor);
          }
          if (!await _hasColumn(
              m, 'app_settings_table', 'safety_buffer_minor')) {
            await m.addColumn(
                db.appSettingsTable, db.appSettingsTable.safetyBufferMinor);
          }
        }
        if (from < 4) {
          // v3 -> v4: goals + goal_contributions. Both tables are new in v4, so
          // a collapsed v1->v4 pass never created them earlier — a plain
          // createTable is safe with no _hasColumn guard.
          await m.createTable(db.goalsTable);
          await m.createTable(db.goalContributionsTable);
        }
        if (from < 5) {
          // v4 -> v5: mortgages + mortgage_payments. Both tables are new in v5,
          // so a collapsed v1->v5 pass never created them earlier — a plain
          // createTable is safe with no _hasColumn guard.
          await m.createTable(db.mortgagesTable);
          await m.createTable(db.mortgagePaymentsTable);
        }
        if (from < 6) {
          // v5 -> v6: add the account budget `role` column. Additive with a
          // 'spending' default. Guarded by _hasColumn because a collapsed
          // v1->v6 pass may have built accounts_table with today's full column
          // set already (this codebase can't use drift's versioned schema CLI —
          // see the class doc — so createTable has no historical snapshot).
          if (!await _hasColumn(m, 'accounts_table', 'role')) {
            await m.addColumn(db.accountsTable, db.accountsTable.role);
          }
          // Default mapping: existing savings-type cards become the savings role;
          // every other row keeps the column's 'spending' default.
          await m.database.customStatement(
            "UPDATE accounts_table SET role = 'savings' WHERE type = 'savings'",
          );
        }
        if (from < 7) {
          // v6 -> v7: add the allocation_plan_rules table and the settings
          // source-account column for the manual card-based allocation plan,
          // then drop the two old bucket-allocation tables now that the new
          // plan fully replaces them (Task 9). Raw `customStatement` with the
          // literal snake_case table names — not a table accessor — because
          // the Dart table classes no longer exist to generate one.
          await m.createTable(db.allocationPlanRulesTable);
          if (!await _hasColumn(
              m, 'app_settings_table', 'allocation_source_account_id')) {
            await m.addColumn(db.appSettingsTable,
                db.appSettingsTable.allocationSourceAccountId);
          }
          await m.database
              .customStatement('DROP TABLE IF EXISTS income_allocations_table');
          await m.database.customStatement(
              'DROP TABLE IF EXISTS allocation_directions_table');
        }
      },
      beforeOpen: (details) async {
        await db.customStatement('PRAGMA foreign_keys = ON');
      },
    );

/// True if `table` already has a column named `column`. Used to guard
/// `addColumn` calls that might otherwise run twice against the same
/// physical table within a single multi-version `onUpgrade` pass (see the
/// comment at the `from < 3` branch above).
Future<bool> _hasColumn(Migrator m, String table, String column) async {
  final rows =
      await m.database.customSelect("PRAGMA table_info($table)").get();
  return rows.any((r) => r.data['name'] == column);
}

Future<void> _seedDefaultCategories(AppDatabase db) async {
  for (var i = 0; i < kDefaultCategories.length; i++) {
    final c = kDefaultCategories[i];
    await db.into(db.categoriesTable).insert(
          CategoriesTableCompanion.insert(
            name: c.name,
            icon: Value(c.icon),
            isDefault: const Value(true),
            sortOrder: Value(i),
          ),
        );
  }
}
