import 'package:drift/drift.dart';
import 'app_database.dart';
import 'default_categories.dart';

/// Stepwise migrations. Each future schema bump adds a `from: N` branch.
///
/// `onUpgrade` uses explicit `Migrator.createTable(...)` calls rather than
/// drift's `stepByStep()` helper: `stepByStep()` requires schema-version code
/// generated by the `drift_dev schema` CLI, and that CLI does not compile in
/// this environment (drift_dev 2.34.0 against drift 2.34.2).
MigrationStrategy buildMigration(AppDatabase db) => MigrationStrategy(
      onCreate: (m) async {
        await m.createAll();
        // Both single-row tables' `id` column defaults to 0 and repositories
        // address the row via `id.equals(0)`. SQLite treats a lone INTEGER
        // column PRIMARY KEY as a rowid alias, so when the id column is
        // omitted from an INSERT, SQLite auto-assigns the next rowid (1)
        // instead of honouring the column's DEFAULT 0 clause. Passing
        // `id: Value(0)` explicitly ensures the seeded row actually lands at
        // id 0.
        await db.into(db.appMetaTable).insert(
              AppMetaTableCompanion.insert(
                id: const Value(0),
                installedAt: DateTime.now(),
              ),
            );
        await db
            .into(db.appSettingsTable)
            .insert(const AppSettingsTableCompanion(id: Value(0)));
        await _seedDefaultCategories(db);
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // v1 -> v2: add the accounts/ledger/categories/recurring tables.
          // `createTable` works without the drift schema CLI (only
          // `stepByStep` needs it), so we create each new table explicitly.
          await m.createTable(db.accountsTable);
          await m.createTable(db.categoriesTable);
          await m.createTable(db.transactionsTable);
          await m.createTable(db.recurringIncomePlansTable);
          await _seedDefaultCategories(db);
        }
      },
      beforeOpen: (details) async {
        await db.customStatement('PRAGMA foreign_keys = ON');
      },
    );

Future<void> _seedDefaultCategories(AppDatabase db) async {
  for (var i = 0; i < kDefaultCategories.length; i++) {
    final c = kDefaultCategories[i];
    await db.into(db.categoriesTable).insert(
          CategoriesTableCompanion.insert(
            name: c.name,
            icon: Value(c.icon),
            isDefault: const Value(true),
            sortOrder: Value(i),
          ),
        );
  }
}
