import 'package:drift/drift.dart';
import 'app_database.dart';
import 'default_allocation.dart';
import 'default_categories.dart';

/// Stepwise migrations. Each future schema bump adds a `from: N` branch.
///
/// `onUpgrade` uses explicit `Migrator.createTable(...)` calls rather than
/// drift's `stepByStep()` helper: `stepByStep()` requires schema-version code
/// generated by the `drift_dev schema` CLI, and that CLI does not compile in
/// this environment (drift_dev 2.34.0 against drift 2.34.2).
MigrationStrategy buildMigration(AppDatabase db) => MigrationStrategy(
      onCreate: (m) async {
        await m.createAll();
        // Both single-row tables' `id` column defaults to 0 and repositories
        // address the row via `id.equals(0)`. SQLite treats a lone INTEGER
        // column PRIMARY KEY as a rowid alias, so when the id column is
        // omitted from an INSERT, SQLite auto-assigns the next rowid (1)
        // instead of honouring the column's DEFAULT 0 clause. Passing
        // `id: Value(0)` explicitly ensures the seeded row actually lands at
        // id 0.
        await db.into(db.appMetaTable).insert(
              AppMetaTableCompanion.insert(
                id: const Value(0),
                installedAt: DateTime.now(),
              ),
            );
        await db
            .into(db.appSettingsTable)
            .insert(const AppSettingsTableCompanion(id: Value(0)));
        await _seedDefaultCategories(db);
        await seedDefaultAllocationTemplate(db);
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // v1 -> v2: add the accounts/ledger/categories/recurring tables.
          // `createTable` works without the drift schema CLI (only
          // `stepByStep` needs it), so we create each new table explicitly.
          await m.createTable(db.accountsTable);
          await m.createTable(db.categoriesTable);
          await m.createTable(db.transactionsTable);
          await m.createTable(db.recurringIncomePlansTable);
          await _seedDefaultCategories(db);
        }
        if (from < 3) {
          // v2 -> v3: category budget columns, variable budget + safety buffer
          // settings, and the two allocation tables.
          //
          // Each `addColumn` is guarded by `_hasColumn`: when this branch
          // runs in the same `onUpgrade` pass as `from < 2` (e.g. a v1
          // install jumping straight to v3), `createTable` above already
          // built `categories_table` using today's full Dart column set (this
          // codebase can't use drift's versioned schema CLI — see the class
          // doc comment — so `createTable` has no historical snapshot to
          // build from), meaning the "new" v3 columns already exist and a
          // second `ADD COLUMN` would throw "duplicate column name".
          if (!await _hasColumn(m, 'categories_table', 'kind')) {
            await m.addColumn(db.categoriesTable, db.categoriesTable.kind);
          }
          if (!await _hasColumn(m, 'categories_table', 'monthly_limit_minor')) {
            await m.addColumn(
                db.categoriesTable, db.categoriesTable.monthlyLimitMinor);
          }
          if (!await _hasColumn(m, 'categories_table', 'weekly_limit_minor')) {
            await m.addColumn(
                db.categoriesTable, db.categoriesTable.weeklyLimitMinor);
          }
          if (!await _hasColumn(
              m, 'app_settings_table', 'variable_budget_minor')) {
            await m.addColumn(
                db.appSettingsTable, db.appSettingsTable.variableBudgetMinor);
          }
          if (!await _hasColumn(
              m, 'app_settings_table', 'safety_buffer_minor')) {
            await m.addColumn(
                db.appSettingsTable, db.appSettingsTable.safetyBufferMinor);
          }
          await m.createTable(db.allocationDirectionsTable);
          await m.createTable(db.incomeAllocationsTable);
          await seedDefaultAllocationTemplate(db);
        }
        if (from < 4) {
          // v3 -> v4: goals + goal_contributions. Both tables are new in v4, so
          // a collapsed v1->v4 pass never created them earlier — a plain
          // createTable is safe with no _hasColumn guard.
          await m.createTable(db.goalsTable);
          await m.createTable(db.goalContributionsTable);
        }
        if (from < 5) {
          // v4 -> v5: mortgages + mortgage_payments. Both tables are new in v5,
          // so a collapsed v1->v5 pass never created them earlier — a plain
          // createTable is safe with no _hasColumn guard.
          await m.createTable(db.mortgagesTable);
          await m.createTable(db.mortgagePaymentsTable);
        }
      },
      beforeOpen: (details) async {
        await db.customStatement('PRAGMA foreign_keys = ON');
      },
    );

/// True if `table` already has a column named `column`. Used to guard
/// `addColumn` calls that might otherwise run twice against the same
/// physical table within a single multi-version `onUpgrade` pass (see the
/// comment at the `from < 3` branch above).
Future<bool> _hasColumn(Migrator m, String table, String column) async {
  final rows =
      await m.database.customSelect("PRAGMA table_info($table)").get();
  return rows.any((r) => r.data['name'] == column);
}

Future<void> _seedDefaultCategories(AppDatabase db) async {
  for (var i = 0; i < kDefaultCategories.length; i++) {
    final c = kDefaultCategories[i];
    await db.into(db.categoriesTable).insert(
          CategoriesTableCompanion.insert(
            name: c.name,
            icon: Value(c.icon),
            isDefault: const Value(true),
            sortOrder: Value(i),
          ),
        );
  }
}
